### ISSUE TITLE
Infinite path generation if in reached_vertex set an edge

### ISSUE THREAD

**Issue by nbdnnm** [GraphWalker/graphwalker-project#105]
If a user made a mistake and typed into reached_vertex an edge name, he will receive an infinite path generation, at least in offline mode
Have a look please on the screenshot

![image](https://cloud.githubusercontent.com/assets/22072588/20459285/aaad77e2-aebb-11e6-86ad-55e09d492536.png)

[googleTranslator.zip](https://github.com/GraphWalker/graphwalker-project/files/601801/googleTranslator.zip)

**Comment by KristianKarl** [comment]
This will be prevented using the new web editor.

**Comment by nilols** [comment]
`ReachedVertex` and `ReachedEdge` should also override the `validate` method like the `ReachedSharedState` does, to validate that the element is of the correct type, otherwise it will just check that it is a `Element`, which both edges and vertices are. I can fix that, and then I purpose that we close this issue.
