### ISSUE TITLE
How to control the verbosity of the test console output?

### ISSUE THREAD

**Issue by arzace20** [GraphWalker/graphwalker-project#132]
Hi,

When I run my test using mvn graphwalker:test command, the -q only applies to maven itself so the INFO tags are the only ones hidden. However, I want to actually hide the main DEBUG messages generated by graphwalker's core.machine classes. Is there a way to do this?

Thanks,
Kevin

**Comment by nilols** [comment]
Hi Kevin,

We use slf4j so it depends on how you have configured logging in your project

As an example I modified a project I currently had open and added a `src/main/resources/logback.xml` file like this
```xml
<configuration>
  <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} [%thread] [%X{trace}] %-5level %logger{20} - %msg%n</pattern>
    </encoder>
  </appender>
  <root level="${root-level:-INFO}">
    <appender-ref ref="CONSOLE"/>
  </root>
</configuration>
```
in the `pom.xml` file I have 
```xml
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.1.9</version>
</dependency>
```

then when running
- `mvn clean graphwalker:test -q` - you'll see INFO messages, due to the default value in `${root-level:-INFO}`
- `mvn clean graphwalker:test -q -Droot-level=DEBUG` - you'll see also debug messages
- `mvn clean graphwalker:test -q -Droot-level=OFF` - you'll see "almost" nothing, but this depends on how other frameworks you use have configured their logging (this can give anyone grey hair =)

I hope this info will help you

**Comment by nilols** [comment]
If you have any other questions or want to follow up more on this try post it [here](https://groups.google.com/forum/#!forum/graphwalker-3) instead, there might be other people there that have the same question as you or others that already know the answer to it, potentially giving you a faster feedback to your questions

I'll close this issue
