### ISSUE TITLE
ArrayLists in v2.6.2 vs v3.2.1

### ISSUE THREAD

**Issue by SKAhster** [GraphWalker/graphwalker-project#9]
Some of our models use hashmaps and arraylists. I don't understand how the syntax changed between v2.6.2 and v3.2.1. For example, the following works fine in the earlier version but not in the latter:

eA / List myArrayList = new ArrayList();
eB [ !myArrayList.contains("Cat") ] / myArrayList.add("Cat");

**Comment by KristianKarl** [comment]
Default for gw2 was to interpret the statements in the models as java. JavaScript was also available.

In gw3, JavaScript is now default.

**Comment by nilols** [comment]
In earlier versions you could use JavaScript or BeanShell as a script language for the actions and guards. In version 3 we use JavaScript, but we also mirror the methods that you define in java, so you have at least twobsolutions. 1. Rewrite your guards and actions to JavaScript or 2. Move the List to Java and delegate the contains() and add() methods. 

Because we use Java scripting there should also be possible to add support for other scripting languages.

**Comment by SKAhster** [comment]
Rather than attempt to move this thread to the GW3 Google Group, I'll just ask a follow up question here. Nils, you suggested that I might try "[moving] the List to Java and delegate the contains() and add() methods". Do you have an example of where you have done that? I'm struggling, being quite new to Java, on how to do that.

**Comment by nilols** [comment]
Look at the [ExampleTest](https://github.com/GraphWalker/graphwalker-project/blob/master/graphwalker-core/src/test/java/org/graphwalker/core/example/ExampleTest.java), there are two methods, isFalse() and isTrue(), they are implemented in java but due to the mirroring that I mentioned earlier you can call them directly from javascript e.g. from a guard or action. In the example the model is created by code, but that doesn't matter you could still define the guards/actions in a graphml model. So it should work if you define a List<> in your implementation and then two public methods where you delegate the contain(String) and add(String) methods.

**Comment by nilols** [comment]
I checked the code, and the methods that is mirrored is only the ones without arguments. I will see if it's possible to add support for methods with arguments

**Comment by nilols** [comment]
I've created a new test [ObjectMirrorTest](https://github.com/GraphWalker/graphwalker-project/blob/master/graphwalker-core/src/test/java/org/graphwalker/core/example/ObjectMirrorTest.java) that verify the mirroing with parameters, if you wanna try it out before the 3.3.0 release you have either build it or get the latest snapshot from the sonatype repository
