### ISSUE TITLE
Convert to java does not provide a .java file but rather an extensionless file

### ISSUE THREAD

**Issue by chamma75** [GraphWalker/graphwalker-project#95]
I noticed that when running the  ConvertFilesTest JUnit test  , the output file gets generated without ".java" extension.
The test ends up with 2 files in the temporary directory (UC01_GW2    and UC01_GW2.java)
The UC01_GW2.java file is empty , while UC01_GW2 contains the generated java code.

Having a look at the DotContextFactory , i can see that the extension is added while building the javaFile name
In the DotContextFactory
     Path jsonFile = Paths.get(folder.toString(), contexts.get(0).getModel().getName() + ".json");

In the JavaContextFactory
     Path javaFile = Paths.get( path.getParent().toString(), context.getModel().getName());

Sounds like it is also needed to add a ".java" extension...
     Path javaFile = Paths.get( path.getParent().toString(), context.getModel().getName() + ".java");

**Comment by KristianKarl** [comment]
There's a fix now in [Latest development standalone CLI - 4.0.0-SNAPSHOT](http://graphwalker.github.io/download/). The handling of the converted output has changed though. It's directed to std output rather than to file.
Please have a look in http://graphwalker.github.io/cli-convert/#version-4

The implementation is done for the CLI, but the original functionality is still there, and needs still to be fixed. So this report is not completely fixed.
